import libs = happly%lib{happly}
import libs += gtest%lib{gtest}

./: exe{main_test}: cxx{main_test} $libs testscript

# The original tests use an implicit conversion
# of negative numbers to values of type 'char'.
#
./: file{main_test.cpp.orig}
